version: "3.8"
services:

    postgres:
        image: postgres
        container_name: cc_postgres_dev
        restart: always
        ports:
            - "5432:5432"
        networks:
            command_center:
                aliases: 
                    - postgres
        volumes:
            - ./ccdata/postgres:/var/lib/postgresql/data
        environment:
            POSTGRES_PASSWORD: 1234
            POSTGRES_DB: commandcenter
            
    rabbitmq:
        image: rabbitmq:3-management
        container_name: cc_rabbitmq_dev
        hostname: rabbitmq
        networks:
            command_center:
                aliases: 
                    - rabbitmq
        volumes:
            - ./ccconfig/rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
            - ./ccdata/rabbitmq/data:/var/lib/rabbitmq/
            - ./ccdata/rabbitmq/logs:/var/log/rabbitmq/
        ports:
            - 5672:5672
            - 15672:15672

networks:
    command_center:
        name: "command_center_dev"
