version: "3.8"
services:

    postgres:
        image: postgres
        container_name: cc_postgres_dev
        restart: always
        ports:
            - "5432:5432"
        networks:
            command_center:
                aliases: 
                    - postgres
        volumes:
            - ./ccdata/postgres:/var/lib/postgresql/data
        environment:
            POSTGRES_PASSWORD: 1234
            POSTGRES_DB: commandcenter

networks:
    command_center:
        name: "command_center_dev"
