version: "3.8"
services:
    command_center:
        container_name: cc_command_center
        restart: always
        networks:
            command_center:
                aliases: 
                    - command_center
        build:
            context: .
            dockerfile: CommandCenter/CommandCenter.Dockerfile
    
    discord_handler:
        container_name: cc_discord_handler
        restart: always
        networks:
            command_center:
                aliases: 
                    - discord_handler
        build:
            context: .
            dockerfile: DiscordHandler/DiscordHandler.Dockerfile

    twitch_handler:
        container_name: cc_twitch_handler
        restart: always
        networks:
            command_center:
                aliases: 
                    - twitch_handler
        build:
            context: .
            dockerfile: TwitchHandler/TwitchHandler.Dockerfile

    postgres:
        image: postgres
        container_name: cc_postgres
        restart: always
        networks:
            command_center:
                aliases: 
                    - postgres
        volumes:
            - ./ccdata/postgres:/var/lib/postgresql/data
        environment:
            POSTGRES_PASSWORD: 1234
            POSTGRES_DB: commandcenter

    rabbitmq:
        image: rabbitmq:3-management
        container_name: cc_rabbitmq
        hostname: rabbitmq
        networks:
            command_center:
                aliases: 
                    - rabbitmq
        volumes:
            - ./ccconfig/rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
            - ./ccdata/rabbitmq/data:/var/lib/rabbitmq/
            - ./ccdata/rabbitmq/logs:/var/log/rabbitmq/

networks:
    command_center:
        name: "command_center"
