version: "3.8"
services:
    command_center:
        container_name: cc_command_center_dev
        networks:
            - command_center:
                aliases: 
                    - command_center
        build:
            context: .
            dockerfile: CommandCenter/CommandCenter.Dockerfile
    
    discord_handler:
        container_name: cc_discord_handler_dev
        networks:
            - command_center:
                aliases: 
                    - discord_handler
        build:
            context: .
            dockerfile: DiscordHandler/DiscordHandler.Dockerfile

    twitch_handler:
        container_name: cc_twitch_handler_dev
        networks:
            - command_center:
                aliases: 
                    - twitch_handler
        build:
            context: .
            dockerfile: TwitchHandler/TwitchHandler.Dockerfile

networks:
    command_center:
        name: "command_center_dev"
